Category
borisdz/plant-palace pull request #11
Opened 2024-05-16 16:28 UTC by l4den

For Category added: DTO, model, exception, repository, service, serviceImpl and controller

2024-05-16 16:42 UTC, borisdz requested changes

2024-05-16 16:42 UTC, borisdz commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/model/Category.java
If you add `@Data` (which is an annotation from Lombok, which we use) before `public class Category` you won't need to manually add getters and setters for the Model which makes the code a bit cleaner,

2024-05-17 07:41 UTC, SazdovaEkaterina submitted a review, later dismissed

2024-05-17 18:58 UTC, borisdz approved these changes

2024-05-18 08:57 UTC, SazdovaEkaterina approved these changes

2024-05-18 08:57 UTC, merged