Initialize backend project
borisdz/plant-palace pull request #3
Opened 2024-04-02 14:23 UTC by borisdz

[Trello card (Click me)](https://trello.com/c/XxckPxxN)

- [ ] Add project structure to repo (.gitkeep)
- [ ] User model, services etc & controller with login and register functionality

- Added project structure (.gitkeep)
- Deleted BCrypt Encoding Password and security configurations and dependencies for oauth and web security because they forced a default login page.
- The login and register functionalities were tested with Postman and they gave the foreseen status codes.

2024-04-02 14:51 UTC, SazdovaEkaterina requested changes

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/.mvn/wrapper/maven-wrapper.jar
Please don't commit jar files or similar. Delete them, commit that and add them to .gitignore before you commit again so git doesn't track them.

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/.gitignore
Use the .gitignore in the root of the repository

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/model/User.java
> +//    @OneToMany(mappedBy = "user", fetch = FetchType.EAGER)
Don't leave commented-out code in the codebase

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/service/impl/AuthServiceImpl.java
> +    //private final PasswordEncoder passwordEncoder;
Remove this commented code as well. It can be added when it is needed

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/service/impl/UserServiceImpl.java
> +    //private final PasswordEncoder passwordEncoder;
Same here

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/web/controller/.gitkeep
This .gitkeep is not needed because there are already files in the folder so you can delete it

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/service/AuthService.java
> +    User login(String username, String password);
This method is not used anywhere, delete it

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/service/impl/.gitkeep
Same thing here, remove all .gitkeep files that aren't in empty folders.

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/repository/UserRepository.java
> +    UserProjection findByRole(Role role);
This seems to have no usages as well, it can be deleted

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/projections/UserProjection.java
Can you check if this projection is needed? I found no usages of it other than UserRepository.findByRole which is also an unused method.

2024-04-02 14:51 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/model/dto/RegisterDto.java
> +    private String repeatPasword;
This property is not needed in the backend, as the password repeat check will be already done in the frontend, so it can be deleted.

2024-04-02 14:57 UTC, SazdovaEkaterina commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/web/controller/AuthController.java
> +@CrossOrigin
```suggestion
@CrossOrigin("http://localhost:4200/")
```

2024-04-02 15:46 UTC, borisdz commented on plant-palace/src/main/java/mk/ukim/finki/uiktp/plantpalace/projections/UserProjection.java
Yes it is only that one usage and an import in the same class. I will delete the whole projection.

2024-04-03 09:02 UTC, SazdovaEkaterina approved these changes

2024-04-03 12:06 UTC, l4den approved these changes

2024-04-03 12:14 UTC, merged